=== matba/magus/composer/src/main/webapp/resources/schema/featureModel.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="featureModel">
	<xs:complexType >
	
	<xs:sequence minOccurs="1" maxOccurs="1">
		<xs:element name="feature" type="featureType"></xs:element>
		<xs:element name="integrityconstraints" type="integrityconstraintsType" ></xs:element>
		<xs:element name="annotations" type="annotationsType" ></xs:element>
		
	</xs:sequence>
</xs:complexType>

</xs:element>


<xs:complexType name="featureType">
	
	<xs:sequence minOccurs="0" maxOccurs="unbounded">
		<xs:element name="feature" minOccurs="0" maxOccurs="unbounded"  type="featureType"></xs:element>
	
		<xs:element name="orgroup" minOccurs="0" maxOccurs="1">
			<xs:complexType>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="feature" type="featureType"></xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="alternative" minOccurs="0" maxOccurs="1">
			<xs:complexType>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="feature" type="featureType"></xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="type" type="xs:string" />
	<xs:attribute name="uuid" type="xs:string" />
</xs:complexType>

<xs:complexType name="integrityconstraintsType">
	<xs:sequence minOccurs="0" maxOccurs="unbounded">
		<xs:element name="integrityconstraint" >
		<xs:complexType>
            <xs:attribute name="name" type="xs:string" />
			<xs:attribute name="type" use="required" >
				<xs:simpleType>
				     <xs:restriction base="xs:string">
				      <xs:enumeration value="requires"/>
				      <xs:enumeration value="excludes"/>

				    </xs:restriction>
				  </xs:simpleType>
			</xs:attribute>
			<xs:attribute name="source" type="xs:string" use="required" />
			<xs:attribute name="target" type="xs:string" use="required" />
        </xs:complexType>
			
		</xs:element>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="annotationsType">
	
	<xs:sequence minOccurs="0" maxOccurs="unbounded">
		<xs:element name="annotation">
			<xs:complexType>	
			
				<xs:sequence minOccurs="1" maxOccurs="1">
					<xs:element name="entities" >
						<xs:complexType>
							<xs:sequence minOccurs="0" maxOccurs="unbounded">
								<xs:element name="entity" >
									<xs:complexType>     
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="type" type="xs:string" use="required" />
										<xs:attribute name="io" type="xs:string" use="required" />
									</xs:complexType>						
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="precondition" type="conditionType" />
					<xs:element name="effect" type="conditionType" />
					
					
				</xs:sequence>
				<xs:attribute name="feature" type="xs:string" use="required" />
			</xs:complexType>
		</xs:element>
	</xs:sequence>
	<xs:attribute name="baseURI" type="xs:string" use="required" />
</xs:complexType>

<xs:complexType name="conditionType">	
	<xs:sequence minOccurs="1" maxOccurs="1	">
		<xs:element name="facts" >
			<xs:complexType>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="fact" >
						<xs:complexType>     
							<xs:attribute name="fact" type="xs:string" use="required" />
							<xs:attribute name="firstEntity" type="xs:string" use="required" />
							<xs:attribute name="secondEntity" type="xs:string" use="required" />
						</xs:complexType>						
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		
	</xs:sequence>

</xs:complexType>
</xs:schema>

=== matba/magus/composer/src/main/webapp/experiments/1/fmcsizes/2000/sm3/fm.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><featureModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://magus.online/resources/schema/featureModel.xsd"><feature name="root" type="mandatory" uuid="b7708014-214c-4591-9f6a-e6e0b661fa6a"><feature name="F1" type="mandatory" uuid="f9fb406f-dd85-4632-a1f2-290a46802ad8"><feature name="F13" type="optional" uuid="fbee7905-54ef-48f5-bf4a-652e70ff3862"/><feature name="A3" type="mandatory" uuid="9472c12c-cba2-4514-9713-3b14191bf427"><alternative><feature name="F14" type="mandatory" uuid="d6bdf648-4993-4340-b5e3-b278838e5449"><alternative/></feature><feature name="F15" type="mandatory" uuid="67504058-6a09-4d3b-90dd-cd41d4d8408e"><alternative><feature name="F16" type="mandatory" uuid="dd3c6cea-fa4e-4746-9a40-de60373775d8"><feature name="F20" type="mandatory" uuid="62037c1f-60c5-4cef-a651-2ca42d61aee3"/></feature><feature name="F17" type="mandatory" uuid="2a857492-2646-4b53-83dd-56ce324375a8"/><feature name="F18" type="optional" uuid="e59b43f5-3b75-4d82-9371-94808880d9ac"/><feature name="F19" type="mandatory" uuid="96713a5f-9b97-4b2a-b4b6-90af73b88644"/></alternative></feature></alternative></feature></feature><feature name="F2" type="optional" uuid="72a0e848-7b68-4029-9b19-0fa1f9768199"><feature name="F7" type="optional" uuid="b07c7da7-f755-4751-bfee-072b5c5ad04c"><alternative><feature name="F11" type="mandatory" uuid="e30adf47-515d-4d23-a751-de0f5116ad41"><alternative/></feature><feature name="F12" type="mandatory" uuid="61f9f4e0-0de8-4008-a952-65e0c717c8ff"><alternative/></feature></alternative></feature></feature><feature name="A1" type="mandatory" uuid="b3c23d7b-e44c-42c8-86de-b3e2b0148caf"><orgroup><feature name="F3" type="mandatory" uuid="06cbfb9e-bed8-4a41-80cb-7b5612a911f7"><orgroup/></feature><feature name="F4" type="mandatory" uuid="9ce7ee26-108b-49cf-96d0-ad780e69543c"><orgroup/></feature></orgroup></feature><feature name="A2" type="mandatory" uuid="f9b14403-0519-45be-9510-637a8f6d6e0a"><alternative><feature name="F5" type="mandatory" uuid="eb417dcd-9a77-4a20-8bdc-50b61fb80907"><alternative><feature name="F21" type="optional" uuid="79ea0bfe-0d36-43b1-bd62-cc5f5c545e91"/></alternative></feature><feature name="F6" type="mandatory" uuid="b945da86-1edd-4089-983c-1fbe887fb75f"><alternative><feature name="F8" type="optional" uuid="26ed341d-011a-4aed-a2eb-8f5f5748fee2"/><feature name="F9" type="optional" uuid="b1563a6d-08d9-4fa3-97e1-fa6b867d1aee"><feature name="F22" type="optional" uuid="08418af9-28e3-47b0-818e-ea19c62aa4ee"/><feature name="F23" type="mandatory" uuid="4cfdab1e-4a10-4e18-aff3-d9dfc451e51d"/><feature name="F24" type="mandatory" uuid="0263c0a5-c2f0-4bd5-99b5-d85326e9399b"><feature name="F27" type="optional" uuid="ef343daa-725b-479d-afe8-ec390187125b"/><feature name="F28" type="optional" uuid="77bf8506-a2d2-4a46-a257-d8dc96fbd988"/><feature name="F29" type="mandatory" uuid="bfb679bc-6bc2-4824-b6d3-efb5653e6b59"/></feature><feature name="A4" type="mandatory" uuid="46709e00-b35b-49f8-a78a-b1561534457a"><orgroup><feature name="F25" type="mandatory" uuid="a74a468e-6528-488d-acdc-21e1a4a17ae5"><orgroup/></feature><feature name="F26" type="mandatory" uuid="f0709ca3-a6a5-4ec4-8882-753925887dc2"><orgroup/></feature></orgroup></feature></feature><feature name="F10" type="mandatory" uuid="78319771-555f-4f5f-a874-9c9b0a342a77"/></alternative></feature></alternative></feature></feature><integrityconstraints><integrityconstraint source="F7" target="F19" type="requires"/></integrityconstraints><annotations baseURI="http://magus.online/eval/svs/fTTFeatureModel59"><annotation feature="root"><entities><entity io="none" name="vc86ecfd281" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c86ecfd28"/><entity io="none" name="vc04d7f5631" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c04d7f563"/></entities><precondition><facts/></precondition><effect><facts/></effect></annotation><annotation feature="F1"><entities><entity io="none" name="vc3b9372901" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c3b937290"/><entity io="none" name="vcfd79af2a1" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#cfd79af2a"/></entities><precondition><facts/></precondition><effect><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p3d92ae92" firstEntity="#vc04d7f5631" secondEntity="#vcfd79af2a1"/><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p4965f6d4" firstEntity="#vc86ecfd281" secondEntity="#vc3b9372901"/></facts></effect></annotation><annotation feature="F13"><entities><entity io="none" name="vc52df7e2d2" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c52df7e2d"/><entity io="none" name="vc20fa213b1" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c20fa213b"/><entity io="none" name="vc52df7e2d1" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c52df7e2d"/></entities><precondition><facts/></precondition><effect><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p3d92ae92" firstEntity="#vc04d7f5631" secondEntity="#vcfd79af2a1"/><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#pc08f41eb" firstEntity="#vc86ecfd281" secondEntity="#vc3b9372901"/><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#pf9ebb79b" firstEntity="#vc52df7e2d1" secondEntity="#vc86ecfd281"/></facts></effect></annotation><annotation feature="A3"><entities><entity io="none" name="vc52df7e2d3" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c52df7e2d"/><entity io="none" name="vc616a72771" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c616a7277"/><entity io="none" name="vc9c7728531" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c9c772853"/><entity io="none" name="vcfd79af2a2" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#cfd79af2a"/></entities><precondition><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#pa1b344cd" firstEntity="#vcfd79af2a2" secondEntity="#vc52df7e2d3"/></facts></precondition><effect><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#pde4c98ab" firstEntity="#vc9c7728531" secondEntity="#vc3b9372901"/></facts></effect></annotation><annotation feature="F14"><entities><entity io="none" name="vc86ecfd282" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c86ecfd28"/><entity io="none" name="vc7b3db5d71" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c7b3db5d7"/></entities><precondition><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#pa1b344cd" firstEntity="#vcfd79af2a2" secondEntity="#vc52df7e2d3"/></facts></precondition><effect><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p0ff27b4f" firstEntity="#vc3b9372901" secondEntity="#vc7b3db5d71"/><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p4cbf5fcd" firstEntity="#vc7b3db5d71" secondEntity="#vc52df7e2d3"/></facts></effect></annotation><annotation feature="F15"><entities><entity io="none" name="vcfd03e40f1" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#cfd03e40f"/></entities><precondition><facts/></precondition><effect><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p3591a350" firstEntity="#vc616a72771" secondEntity="#vc3b9372901"/></facts></effect></annotation><annotation feature="F16"><entities><entity io="none" name="vcfd79af2a3" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#cfd79af2a"/><entity io="none" name="vc7b825b021" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c7b825b02"/></entities><precondition><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#pcc16bd24" firstEntity="#vc9c7728531" secondEntity="#vc7b825b021"/></facts></precondition><effect><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p96ae490e" firstEntity="#vcfd79af2a3" secondEntity="#vc3b9372901"/></facts></effect></annotation><annotation feature="F20"><entities><entity io="none" name="vc0a670e541" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c0a670e54"/><entity io="none" name="vcdd525e111" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#cdd525e11"/><entity io="none" name="vcfd03e40f3" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#cfd03e40f"/><entity io="none" name="vcfd03e40f2" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#cfd03e40f"/></entities><precondition><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#pcc16bd24" firstEntity="#vc9c7728531" secondEntity="#vc7b825b021"/></facts></precondition><effect><facts/></effect></annotation><annotation feature="F17"><entities><entity io="none" name="vc0a670e542" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c0a670e54"/></entities><precondition><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p21825076" firstEntity="#vc52df7e2d3" secondEntity="#vc0a670e542"/></facts></precondition><effect><facts/></effect></annotation><annotation feature="F18"><entities><entity io="none" name="vc9813ee281" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c9813ee28"/></entities><precondition><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#p3b089959" firstEntity="#vc86ecfd281" secondEntity="#vcfd03e40f1"/></facts></precondition><effect><facts><fact fact="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#pc75ad921" firstEntity="#vc9813ee281" secondEntity="#vc86ecfd281"/></facts></effect></annotation><annotation feature="F19"><entities><entity io="none" name="vc9c7728532" type="http://ls3.rnet.ryerson.ca/people/mahdi/magus/owl/eval.owl#c9c772853"/></entities><precondition><facts/></precondition><effect><facts/
