=== matba/magus/composer/src/main/webapp/resources/schema/servicemashupconfiguration.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


	<xs:element name="configuration">
		<xs:complexType >
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="ontologies" type="ontologiesType"></xs:element>
				<xs:element name="featuremodel" type="featuremodelType" ></xs:element>
				<xs:element name="services" type="servicesType" ></xs:element>
				
			</xs:sequence>
			<xs:attribute name="base" type="xs:string" />
		</xs:complexType>
		
	</xs:element>
	
	<xs:complexType name="ontologiesType">
	
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			
			<xs:element name="ontology" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="address" type="xs:string" use="required" />
					
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		
	</xs:complexType>
	
	<xs:complexType name="featuremodelType">
	
		<xs:attribute name="address" type="xs:string" use="required" />
		
	</xs:complexType>
	
	<xs:complexType name="servicesType">
	
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			
			<xs:element name="service" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="address" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		
	</xs:complexType>
</xs:schema>

=== matba/magus/composer/src/main/webapp/experiments/1/svssizes/150/configuration.xml
<?xml version="1.0" encoding="UTF-16"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://magus.online/resources/schema/servicemashupconfiguration.xsd"><ontologies><ontology address="contextModel.xml"/></ontologies><featuremodel address="fm.xml"/><services><service address="services/ServiceC4S3.xml"/><service address="services/ServiceC25S2.xml"/><service address="services/ServiceC101S3.xml"/><service address="services/ServiceC94S6.xml"/><service address="services/ServiceC9S1.xml"/><service address="services/ServiceC94S9.xml"/><service address="services/ServiceC20S3.xml"/><service address="services/ServiceC1101S5.xml"/><service address="services/ServiceC10S4.xml"/><service address="services/ServiceC1568S11.xml"/><service address="services/ServiceC9S2.xml"/><service address="services/ServiceC1101S13.xml"/><service address="services/ServiceC1568S3.xml"/><service address="services/ServiceC10S2.xml"/><service address="services/ServiceC6S4.xml"/><service address="services/ServiceC1101S1.xml"/><service address="services/ServiceC101S2.xml"/><service address="services/ServiceC328S1.xml"/><service address="services/ServiceC784S1.xml"/><service address="services/ServiceC20S5.xml"/><service address="services/ServiceC6S3.xml"/><service address="services/ServiceC784S6.xml"/><service address="services/ServiceC18S3.xml"/><service address="services/ServiceC1101S8.xml"/><service address="services/ServiceC22S4.xml"/><service address="services/ServiceC18S1.xml"/><service address="services/ServiceC1568S4.xml"/><service address="services/ServiceC784S4.xml"/><service address="services/ServiceC1670S6.xml"/><service address="services/ServiceC13S1.xml"/><service address="services/ServiceC44S6.xml"/><service address="services/ServiceC1101S9.xml"/><service address="services/ServiceC1670S4.xml"/><service address="services/ServiceC1101S4.xml"/><service address="services/ServiceC13S4.xml"/><service address="services/ServiceC1101S14.xml"/><service address="services/ServiceC101S1.xml"/><service address="services/ServiceC36S2.xml"/><service address="services/ServiceC78S4.xml"/><service address="services/ServiceC784S7.xml"/><service address="services/ServiceC25S5.xml"/><service address="services/ServiceC7S2.xml"/><service address="services/ServiceC22S5.xml"/><service address="services/ServiceC1670S9.xml"/><service address="services/ServiceC22S3.xml"/><service address="services/ServiceC1101S3.xml"/><service address="services/ServiceC1568S6.xml"/><service address="services/ServiceC78S3.xml"/><service address="services/ServiceC5S1.xml"/><service address="services/ServiceC1568S2.xml"/><service address="services/ServiceC7S3.xml"/><service address="services/ServiceC44S4.xml"/><service address="services/ServiceC94S7.xml"/><service address="services/ServiceC25S1.xml"/><service address="services/ServiceC328S8.xml"/><service address="services/ServiceC6S5.xml"/><service address="services/ServiceC101S5.xml"/><service address="services/ServiceC6S2.xml"/><service address="services/ServiceC5S3.xml"/><service address="services/ServiceC2S1.xml"/><service address="services/ServiceC328S6.xml"/><service address="services/ServiceC1670S1.xml"/><service address="services/ServiceC2S3.xml"/><service address="services/ServiceC784S2.xml"/><service address="services/ServiceC16S5.xml"/><service address="services/ServiceC18S2.xml"/><service address="services/ServiceC328S2.xml"/><service address="services/ServiceC15S1.xml"/><service address="services/ServiceC784S5.xml"/><service address="services/ServiceC1670S7.xml"/><service address="services/ServiceC1568S10.xml"/><service address="services/ServiceC25S4.xml"/><service address="services/ServiceC1568S8.xml"/><service address="services/ServiceC3S2.xml"/><service address="services/ServiceC13S2.xml"/><service address="services/ServiceC22S6.xml"/><service address="services/ServiceC10S1.xml"/><service address="services/ServiceC6S1.xml"/><service address="services/ServiceC16S1.xml"/><service address="services/ServiceC44S3.xml"/><service address="services/ServiceC2S2.xml"/><service address="services/ServiceC78S1.xml"/><service address="services/ServiceC784S3.xml"/><service address="services/ServiceC78S8.xml"/><service address="services/ServiceC16S3.xml"/><service address="services/ServiceC94S8.xml"/><service address="services/ServiceC13S3.xml"/><service address="services/ServiceC1101S12.xml"/><service address="services/ServiceC4S1.xml"/><service address="services/ServiceC94S2.xml"/><service address="services/ServiceC78S7.xml"/><service address="services/ServiceC94S3.xml"/><service address="services/ServiceC78S5.xml"/><service address="services/ServiceC328S4.xml"/><service address="services/ServiceC94S1.xml"/><service address="services/ServiceC1568S9.xml"/><service address="services/ServiceC3S3.xml"/><service address="services/ServiceC3S1.xml"/><service address="services/ServiceC78S2.xml"/><service address="services/ServiceC20S4.xml"/><service address="services/ServiceC44S2.xml"/><service address="services/ServiceC22S2.xml"/><service address="services/ServiceC4S4.xml"/><service address="services/ServiceC7S1.xml"/><service address="services/ServiceC1670S5.xml"/><service address="services/ServiceC20S1.xml"/><service address="services/ServiceC44S1.xml"/><service address="services/ServiceC44S5.xml"/><service address="services/ServiceC78S6.xml"/><service address="services/ServiceC36S4.xml"/><service address="services/ServiceC15S2.xml"/><service address="services/ServiceC9S3.xml"/><service address="services/ServiceC16S2.xml"/><service address="services/ServiceC1101S11.xml"/><service address="services/ServiceC328S7.xml"/><service address="services/ServiceC1101S10.xml"/><service address="services/ServiceC1568S5.xml"/><service address="services/ServiceC36S6.xml"/><service address="services/ServiceC18S4.xml"/><service address="services/ServiceC36S5.xml"/><service address="services/ServiceC15S3.xml"/><service address="services/ServiceC20S2.xml"/><service address="services/ServiceC1670S3.xml"/><service address="services/ServiceC1568S7.xml"/><service address="services/ServiceC94S5.xml"/><service address="services/ServiceC328S5.xml"/><service address="services/ServiceC4S2.xml"/><service address="services/ServiceC6S6.xml"/><service address="services/ServiceC1568S1.xml"/><service address="services/ServiceC5S2.xml"/><service address="services/ServiceC22S1.xml"/><service address="services/ServiceC36S3.xml"/><service address="services/ServiceC10S3.xml"/><service address="services/ServiceC36S1.xml"/><service address="services/ServiceC101S6.xml"/><service address="services/ServiceC1670S2.xml"/><service address="services/ServiceC328S3.xml"/><service address="services/ServiceC101S4.xml"/><service address="services/ServiceC94S4.xml"/><service address="services/ServiceC1101S7.xml"/><service address="services/ServiceC25S6.xml"/><service address="services/ServiceC1101S6.xml"/><service address="services/ServiceC1670S8.xml"/><service address="services/ServiceC16S4.xml"/><service address="services/ServiceC25S3.xml"/><service address="services/ServiceC1101S2.xml"/></services></configuration>
